app:
    useFakeCustomerRepo: false
info:
    app:
        description: Master Spring Boot
        name: Spring Boot Master Class Course
        version: 1.0.0
    company:
        name: Amigoscode
management:
    endpoint:
        health:
            show-details: always
    endpoints:
        web:
            exposure:
                include: health, info
    info:
        env:
            enabled: true
server:
    error:
        include-binding-errors: always
        include-message: always
        include-stacktrace: on_param
spring:
    datasource:
        driver-class-name: org.h2.Driver
        password: ''
        url: jdbc:h2:mem:testdb
        username: sa
    h2:
        console:
            enabled: true
            path: /h2
    jpa:
        database-platform: org.hibernate.dialect.H2Dialect
        show-sql: true
